# Generated by Django 5.2.7 on 2025-10-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='gallery/')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('client_name', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('residential', 'Residences'), ('hotels', 'Hotels'), ('institutions', 'Institutions'), ('commercial', 'Commercial'), ('interiors', 'Interiors'), ('public_spaces', 'Public Spaces'), ('completed', 'Completed Projects'), ('upcoming', 'Upcoming Projects')], max_length=50)),
                ('image1', models.ImageField(upload_to='projects/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='projects/')),
            ],
        ),
    ]
