# Generated by Django 5.2.9 on 2025-12-30 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_servicecategory_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecategory',
            name='description',
        ),
    ]
