# Generated by Django 5.2.9 on 2026-01-13 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_servicecategory_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='service',
            name='location',
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
