# Generated by Django 5.2 on 2026-02-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_directors_teammember_delete_gallery_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directors',
            options={'verbose_name': 'Director', 'verbose_name_plural': 'Directors'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'verbose_name': 'Team Member', 'verbose_name_plural': 'Team Members'},
        ),
        migrations.AddField(
            model_name='directors',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
